In [2]:
import numpy as np
#Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
#a) Addition of 2 in all the element
arr1=np.array([1,2,3,4,5])
print("Original array:",arr1)
print("After adding 2:",arr1+2)

#b) Multiply 3 with all the elements
print("after multiplying 3:",arr1*3)

#c) Divide every element by 2
print("after dividing by 2:",arr1/2)






Original array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
after multiplying 3: [ 3  6  9 12 15]
after dividing by 2: [0.5 1.  1.5 2.  2.5]


In [7]:
#Q.2 Questions on Basic NumPy Array:
#a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
arr2=np.array([1,2,3,6,4,5])
print("Reversed Array:",arr2[::-1])


#b) Find the most frequent value and their indice(s) in the following arrays:

def find_mode(arr):
    unique_values,counts=np.unique(arr,return_counts=True)
    max_count_index=np.argmax(counts)
    most_frequent=unique_values[max_count_index]
    return most_frequent

#i. x = np.array([1,2,3,4,5,1,2,1,1,1])

x=np.array([1,2,3,4,5,1,2,1,1,1])
x_mode=find_mode(x)
print("Most frequent in x:",x_mode,"Indices:",np.where(x==x_mode)[0])

#ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

y=np.array([1,1,1,2,3,4,2,4,3,3])
y_mode=find_mode(y)
print("Most frequent in y:",y_mode,"Indices:",np.where(y==y_mode)[0])

Reversed Array: [5 4 6 3 2 1]
Most frequent in x: 1 Indices: [0 5 7 8 9]
Most frequent in y: 1 Indices: [0 1 2]


In [9]:
#Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:
#a) Access 1st row, 2nd column
arr3=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Element at [0,1]:",arr3[0,1])

#b) Access 3rd row, 1st column
print("Element at [2,0]:",arr3[2,0])

Element at [0,1]: 20
Element at [2,0]: 70


In [10]:
#Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?
Savree=np.linspace(10,100,25)
print("Array:",Savree)
print("Dimensions:",Savree.ndim)
print("Shape:",Savree.shape)
print("Total elements:",Savree.size)
print("Data type:",Savree.dtype)
print("Bytes consumed:",Savree.nbytes)
print("Transposed Array using reshape():",Savree.reshape(25,1))
print("Using T:",Savree.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Bytes consumed: 200
Transposed Array using reshape(): [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [11]:
#Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.
ucs420_Savree=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("Mean:",np.mean(ucs420_Savree))
print("Median:",np.median(ucs420_Savree))
print("Max:",np.max(ucs420_Savree))
print("Min:",np.min(ucs420_Savree))
print("Unique Elements:",np.unique(ucs420_Savree))
reshaped_ucs420_Savree=ucs420_Savree.reshape(4,3)
print("Reshaped Array:",reshaped_ucs420_Savree)
resized_ucs420_Savree=np.resize(ucs420_Savree,(2,3))
print("Resized Array:",resized_ucs420_Savree)



Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array: [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array: [[10 20 30]
 [40 50 60]]
